import pytest
import tempfile
from pathlib import Path


@pytest.fixture
def temp_dir():
    """Provide a temporary directory for tests."""
    with tempfile.TemporaryDirectory() as tmpdir:
        yield Path(tmpdir)


@pytest.fixture
def sample_cpp_content():
    """Sample C++ source code for testing."""
    return """
#include <iostream>

inline int add(int a, int b) {
    return a + b;
}

class Calculator {
public:
    virtual int multiply(int a, int b) {
        return a * b;
    }
};

class AdvancedCalculator : public Calculator {
public:
    virtual int multiply(int a, int b) {
        return a * b;
    }
};

int main() {
    inline int x = add(1, 2);
    return 0;
}
"""


@pytest.fixture
def sample_cpp_file(temp_dir, sample_cpp_content):
    """Create a sample C++ file in temp directory."""
    cpp_file = temp_dir / "test.cpp"
    cpp_file.write_text(sample_cpp_content)
    return cpp_file


@pytest.fixture
def sample_asm_content():
    """Sample assembly output."""
    return """; Listing generated by Microsoft (R) Optimizing Compiler Version 19.29.30133.0

    TITLE   C:\\test.cpp
    .686P
    .XMM
    include listing.inc
    .model  flat

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

PUBLIC  _add
; Function compile flags: /Ogtp
_TEXT   SEGMENT
_a$ = 8                                       ; size = 4
_b$ = 12                                      ; size = 4
_add    PROC
        mov     eax, DWORD PTR _a$[esp-4]
        add     eax, DWORD PTR _b$[esp-4]
        ret     0
_add    ENDP
_TEXT   ENDS
END
"""


@pytest.fixture
def sample_asm_file(temp_dir, sample_asm_content):
    """Create a sample assembly file."""
    asm_file = temp_dir / "test.asm"
    asm_file.write_text(sample_asm_content)
    return asm_file
